 var countries2 = [
    {"name":"Afghanistan",label:"AF",phone:93},
    {"name":"Aland Islands",label:"AX",phone:358},
    {"name":"Albania",label:"AL",phone:355},
    {"name":"Algeria",label:"DZ",phone:213},
    {"name":"American Samoa",label:"AS",phone:1684},
    {"name":"Andorra",label:"AD",phone:376},
    {"name":"Angola",label:"AO",phone:244},
    {"name":"Anguilla",label:"AI",phone:1264},
    {"name":"Antarctica",label:"AQ",phone:672},
    {"name":"Antigua and Barbuda",label:"AG",phone:1268},
    {"name":"Argentina",label:"AR",phone:54},
    {"name":"Armenia",label:"AM",phone:374},
    {"name":"Aruba",label:"AW",phone:297},
    {"name":"Australia",label:"AU",phone:61},
    {"name":"Austria",label:"AT",phone:43},
    {"name":"Azerbaijan",label:"AZ",phone:994},
    {"name":"Bahamas",label:"BS",phone:1242},
    {"name":"Bahrain",label:"BH",phone:973},
    {"name":"Bangladesh",label:"BD",phone:880},
    {"name":"Barbados",label:"BB",phone:1246},
    {"name":"Belarus",label:"BY",phone:375},
    {"name":"Belgium",label:"BE",phone:32},
    {"name":"Belize",label:"BZ",phone:501},
    {"name":"Benin",label:"BJ",phone:229},
    {"name":"Bermuda",label:"BM",phone:1441},
    {"name":"Bhutan",label:"BT",phone:975},
    {"name":"Bolivia",label:"BO",phone:591},
    {"name":"Bonaire, Sint Eustatius and Saba",label:"BQ",phone:599},
    {"name":"Bosnia and Herzegovina",label:"BA",phone:387},
    {"name":"Botswana",label:"BW",phone:267},
    {"name":"Bouvet Island",label:"BV",phone:55},
    {"name":"Brazil",label:"BR",phone:55},
    {"name":"British Indian Ocean Territory",label:"IO",phone:246},
    {"name":"Brunei Darussalam",label:"BN",phone:673},
    {"name":"Bulgaria",label:"BG",phone:359},
    {"name":"Burkina Faso",label:"BF",phone:226},
    {"name":"Burundi",label:"BI",phone:257},
    {"name":"Cambodia",label:"KH",phone:855},
    {"name":"Cameroon",label:"CM",phone:237},
    {"name":"Canada",label:"CA",phone:1},
    {"name":"Cape Verde",label:"CV",phone:238},
    {"name":"Cayman Islands",label:"KY",phone:1345},
    {"name":"Central African Republic",label:"CF",phone:236},
    {"name":"Chad",label:"TD",phone:235},
    {"name":"Chile",label:"CL",phone:56},
    {"name":"China",label:"CN",phone:86},
    {"name":"Christmas Island",label:"CX",phone:61},
    {"name":"Cocos (Keeling) Islands",label:"CC",phone:672},
    {"name":"Colombia",label:"CO",phone:57},
    {"name":"Comoros",label:"KM",phone:269},
    {"name":"Congo",label:"CG",phone:242},
    {"name":"Congo, Democratic Republic of the Congo",label:"CD",phone:242},
    {"name":"Cook Islands",label:"CK",phone:682},
    {"name":"Costa Rica",label:"CR",phone:506},
    {"name":"Cote D'Ivoire",label:"CI",phone:225},
    {"name":"Croatia",label:"HR",phone:385},
    {"name":"Cuba",label:"CU",phone:53},
    {"name":"Curacao",label:"CW",phone:599},
    {"name":"Cyprus",label:"CY",phone:357},
    {"name":"Czech Republic",label:"CZ",phone:420},
    {"name":"Denmark",label:"DK",phone:45},
    {"name":"Djibouti",label:"DJ",phone:253},
    {"name":"Dominica",label:"DM",phone:1767},
    {"name":"Dominican Republic",label:"DO",phone:1809},
    {"name":"Ecuador",label:"EC",phone:593},
    {"name":"Egypt",label:"EG",phone:20},
    {"name":"El Salvador",label:"SV",phone:503},
    {"name":"Equatorial Guinea",label:"GQ",phone:240},
    {"name":"Eritrea",label:"ER",phone:291},
    {"name":"Estonia",label:"EE",phone:372},
    {"name":"Ethiopia",label:"ET",phone:251},
    {"name":"Falkland Islands (Malvinas)",label:"FK",phone:500},
    {"name":"Faroe Islands",label:"FO",phone:298},
    {"name":"Fiji",label:"FJ",phone:679},
    {"name":"Finland",label:"FI",phone:358},
    {"name":"France",label:"FR",phone:33},
    {"name":"French Guiana",label:"GF",phone:594},
    {"name":"French Polynesia",label:"PF",phone:689},
    {"name":"French Southern Territories",label:"TF",phone:262},
    {"name":"Gabon",label:"GA",phone:241},
    {"name":"Gambia",label:"GM",phone:220},
    {"name":"Georgia",label:"GE",phone:995},
    {"name":"Germany",label:"DE",phone:49},
    {"name":"Ghana",label:"GH",phone:233},
    {"name":"Gibraltar",label:"GI",phone:350},
    {"name":"Greece",label:"GR",phone:30},
    {"name":"Greenland",label:"GL",phone:299},
    {"name":"Grenada",label:"GD",phone:1473},
    {"name":"Guadeloupe",label:"GP",phone:590},
    {"name":"Guam",label:"GU",phone:1671},
    {"name":"Guatemala",label:"GT",phone:502},
    {"name":"Guernsey",label:"GG",phone:44},
    {"name":"Guinea",label:"GN",phone:224},
    {"name":"Guinea-Bissau",label:"GW",phone:245},
    {"name":"Guyana",label:"GY",phone:592},
    {"name":"Haiti",label:"HT",phone:509},
    {"name":"Heard Island and Mcdonald Islands",label:"HM",phone:0},
    {"name":"Holy See (Vatican City State)",label:"VA",phone:39},
    {"name":"Honduras",label:"HN",phone:504},
    {"name":"Hong Kong",label:"HK",phone:852},
    {"name":"Hungary",label:"HU",phone:36},
    {"name":"Iceland",label:"IS",phone:354},
    {"name":"India",label:"IN",phone:91},
    {"name":"Indonesia",label:"ID",phone:62},
    {"name":"Iran, Islamic Republic of",label:"IR",phone:98},
    {"name":"Iraq",label:"IQ",phone:964},
    {"name":"Ireland",label:"IE",phone:353},
    {"name":"Isle of Man",label:"IM",phone:44},
    {"name":"Israel",label:"IL",phone:972},
    {"name":"Italy",label:"IT",phone:39},
    {"name":"Jamaica",label:"JM",phone:1876},
    {"name":"Japan",label:"JP",phone:81},
    {"name":"Jersey",label:"JE",phone:44},
    {"name":"Jordan",label:"JO",phone:962},
    {"name":"Kazakhstan",label:"KZ",phone:7},
    {"name":"Kenya",label:"KE",phone:254},
    {"name":"Kiribati",label:"KI",phone:686},
    {"name":"Korea, Democratic People's Republic of",label:"KP",phone:850},
    {"name":"Korea, Republic of",label:"KR",phone:82},
    {"name":"Kosovo",label:"XK",phone:381},
    {"name":"Kuwait",label:"KW",phone:965},
    {"name":"Kyrgyzstan",label:"KG",phone:996},
    {"name":"Lao People's Democratic Republic",label:"LA",phone:856},
    {"name":"Latvia",label:"LV",phone:371},
    {"name":"Lebanon",label:"LB",phone:961},
    {"name":"Lesotho",label:"LS",phone:266},
    {"name":"Liberia",label:"LR",phone:231},
    {"name":"Libyan Arab Jamahiriya",label:"LY",phone:218},
    {"name":"Liechtenstein",label:"LI",phone:423},
    {"name":"Lithuania",label:"LT",phone:370},
    {"name":"Luxembourg",label:"LU",phone:352},
    {"name":"Macao",label:"MO",phone:853},
    {"name":"Macedonia, the Former Yugoslav Republic of",label:"MK",phone:389},
    {"name":"Madagascar",label:"MG",phone:261},
    {"name":"Malawi",label:"MW",phone:265},
    {"name":"Malaysia",label:"MY",phone:60},
    {"name":"Maldives",label:"MV",phone:960},
    {"name":"Mali",label:"ML",phone:223},
    {"name":"Malta",label:"MT",phone:356},
    {"name":"Marshall Islands",label:"MH",phone:692},
    {"name":"Martinique",label:"MQ",phone:596},
    {"name":"Mauritania",label:"MR",phone:222},
    {"name":"Mauritius",label:"MU",phone:230},
    {"name":"Mayotte",label:"YT",phone:269},
    {"name":"Mexico",label:"MX",phone:52},
    {"name":"Micronesia, Federated States of",label:"FM",phone:691},
    {"name":"Moldova, Republic of",label:"MD",phone:373},
    {"name":"Monaco",label:"MC",phone:377},
    {"name":"Mongolia",label:"MN",phone:976},
    {"name":"Montenegro",label:"ME",phone:382},
    {"name":"Montserrat",label:"MS",phone:1664},
    {"name":"Morocco",label:"MA",phone:212},
    {"name":"Mozambique",label:"MZ",phone:258},
    {"name":"Myanmar",label:"MM",phone:95},
    {"name":"Namibia",label:"NA",phone:264},
    {"name":"Nauru",label:"NR",phone:674},
    {"name":"Nepal",label:"NP",phone:977},
    {"name":"Netherlands",label:"NL",phone:31},
    {"name":"Netherlands Antilles",label:"AN",phone:599},
    {"name":"New Caledonia",label:"NC",phone:687},
    {"name":"New Zealand",label:"NZ",phone:64},
    {"name":"Nicaragua",label:"NI",phone:505},
    {"name":"Niger",label:"NE",phone:227},
    {"name":"Nigeria",label:"NG",phone:234},
    {"name":"Niue",label:"NU",phone:683},
    {"name":"Norfolk Island",label:"NF",phone:672},
    {"name":"Northern Mariana Islands",label:"MP",phone:1670},
    {"name":"Norway",label:"NO",phone:47},
    {"name":"Oman",label:"OM",phone:968},
    {"name":"Pakistan",label:"PK",phone:92},
    {"name":"Palau",label:"PW",phone:680},
    {"name":"Palestinian Territory, Occupied",label:"PS",phone:970},
    {"name":"Panama",label:"PA",phone:507},
    {"name":"Papua New Guinea",label:"PG",phone:675},
    {"name":"Paraguay",label:"PY",phone:595},
    {"name":"Peru",label:"PE",phone:51},
    {"name":"Philippines",label:"PH",phone:63},
    {"name":"Pitcairn",label:"PN",phone:64},
    {"name":"Poland",label:"PL",phone:48},
    {"name":"Portugal",label:"PT",phone:351},
    {"name":"Puerto Rico",label:"PR",phone:1787},
    {"name":"Qatar",label:"QA",phone:974},
    {"name":"Reunion",label:"RE",phone:262},
    {"name":"Romania",label:"RO",phone:40},
    {"name":"Russian Federation",label:"RU",phone:70},
    {"name":"Rwanda",label:"RW",phone:250},
    {"name":"Saint Barthelemy",label:"BL",phone:590},
    {"name":"Saint Helena",label:"SH",phone:290},
    {"name":"Saint Kitts and Nevis",label:"KN",phone:1869},
    {"name":"Saint Lucia",label:"LC",phone:1758},
    {"name":"Saint Martin",label:"MF",phone:590},
    {"name":"Saint Pierre and Miquelon",label:"PM",phone:508},
    {"name":"Saint Vincent and the Grenadines",label:"VC",phone:1784},
    {"name":"Samoa",label:"WS",phone:684},
    {"name":"San Marino",label:"SM",phone:378},
    {"name":"Sao Tome and Principe",label:"ST",phone:239},
    {"name":"Saudi Arabia",label:"SA",phone:966},
    {"name":"Senegal",label:"SN",phone:221},
    {"name":"Serbia",label:"RS",phone:381},
    {"name":"Serbia and Montenegro",label:"CS",phone:381},
    {"name":"Seychelles",label:"SC",phone:248},
    {"name":"Sierra Leone",label:"SL",phone:232},
    {"name":"Singapore",label:"SG",phone:65},
    {"name":"Sint Maarten",label:"SX",phone:1},
    {"name":"Slovakia",label:"SK",phone:421},
    {"name":"Slovenia",label:"SI",phone:386},
    {"name":"Solomon Islands",label:"SB",phone:677},
    {"name":"Somalia",label:"SO",phone:252},
    {"name":"South Africa",label:"ZA",phone:27},
    {"name":"South Georgia and the South Sandwich Islands",label:"GS",phone:500},
    {"name":"South Sudan",label:"SS",phone:211},
    {"name":"Spain",label:"ES",phone:34},
    {"name":"Sri Lanka",label:"LK",phone:94},
    {"name":"Sudan",label:"SD",phone:249},
    {"name":"Suriname",label:"SR",phone:597},
    {"name":"Svalbard and Jan Mayen",label:"SJ",phone:47},
    {"name":"Swaziland",label:"SZ",phone:268},
    {"name":"Sweden",label:"SE",phone:46},
    {"name":"Switzerland",label:"CH",phone:41},
    {"name":"Syrian Arab Republic",label:"SY",phone:963},
    {"name":"Taiwan, Province of China",label:"TW",phone:886},
    {"name":"Tajikistan",label:"TJ",phone:992},
    {"name":"Tanzania, United Republic of",label:"TZ",phone:255},
    {"name":"Thailand",label:"TH",phone:66},
    {"name":"Timor-Leste",label:"TL",phone:670},
    {"name":"Togo",label:"TG",phone:228},
    {"name":"Tokelau",label:"TK",phone:690},
    {"name":"Tonga",label:"TO",phone:676},
    {"name":"Trinidad and Tobago",label:"TT",phone:1868},
    {"name":"Tunisia",label:"TN",phone:216},
    {"name":"Turkey",label:"TR",phone:90},
    {"name":"Turkmenistan",label:"TM",phone:7370},
    {"name":"Turks and Caicos Islands",label:"TC",phone:1649},
    {"name":"Tuvalu",label:"TV",phone:688},
    {"name":"Uganda",label:"UG",phone:256},
    {"name":"Ukraine",label:"UA",phone:380},
    {"name":"United Arab Emirates",label:"AE",phone:971},
    {"name":"United Kingdom",label:"GB",phone:44},
    {"name":"United States",label:"US",phone:1},
    {"name":"United States Minor Outlying Islands",label:"UM",phone:1},
    {"name":"Uruguay",label:"UY",phone:598},
    {"name":"Uzbekistan",label:"UZ",phone:998},
    {"name":"Vanuatu",label:"VU",phone:678},
    {"name":"Venezuela",label:"VE",phone:58},
    {"name":"Viet Nam",label:"VN",phone:84},
    {"name":"Virgin Islands, British",label:"VG",phone:1284},
    {"name":"Virgin Islands, U.s.",label:"VI",phone:1340},
    {"name":"Wallis and Futuna",label:"WF",phone:681},
    {"name":"Western Sahara",label:"EH",phone:212},
    {"name":"Yemen",label:"YE",phone:967},
    {"name":"Zambia",label:"ZM",phone:260},
    {"name":"Zimbabwe",label:"ZW",phone:263}
];

countries2.map((curr)=>{
    delete curr.name;
    return curr
})
// console.log(countries)

export  {countries2};
